# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
