# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171001_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='book',
        ),
    ]
